services:
  selenoid:
    image: aerokube/selenoid:latest-release
    networks:
      - selenoid_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - C:/Studying/Courses/Mobile/ProjectsMobile/MobileAtomation/browsers.json:/etc/selenoid/browsers.json
      - /tmp/selenoid/video:/opt/selenoid/video
      - /tmp/selenoid/logs:/opt/selenoid/logs
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4445:4444"

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    depends_on:
      - selenoid
    networks:
      - selenoid_network
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

networks:
  selenoid_network:
    driver: bridge
